@startuml
'https://plantuml.com/state-diagram

hide empty description
[*] --> 上锁
上锁 --> 验证长度 : 输入字符
验证长度 --> 上锁 : 字符长度不等于四
验证长度 --> 验证密码 : 字符长度等于四
验证密码 --> 上锁 : 密码错误且次数小于三次
验证密码 --> 锁定 : 密码错误且次数大于等于三次
锁定 --> 上锁 : 120秒后
验证密码 --> [*] : 密码正确


@enduml