@startuml
class College {
- Building[] buildings
- Course[] courses
}

class Course {
- String name
- Building building
}

class Building {
- String name
}

Building "*" --* "1" College : "包含"
Building "1" --* "*" Course : "位于"
Course "*" --* "1" College : "提供"

@enduml